# Generated by Django 3.2.8 on 2021-10-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='StudentInSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(verbose_name='Дата зачисление')),
                ('unjoin_date', models.DateField(blank=True, null=True, verbose_name='Дата отчисления')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sections.section', verbose_name='Секция')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студент в секции',
                'verbose_name_plural': 'Студент в секции',
            },
        ),
    ]
