# Generated by Django 3.2.8 on 2021-10-25 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinsection',
            name='unjoin_date',
        ),
        migrations.AlterField(
            model_name='studentinsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sections.section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='studentinsection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.student', verbose_name='Студент'),
        ),
    ]
