# Generated by Django 3.2.8 on 2021-10-25 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('sections', '0002_auto_20211026_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sections.section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='studentinsection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.student', verbose_name='Студент'),
        ),
    ]
